config/routes.rb
Rails.application.routes.draw do
  resources :songtopics do
    member do
      post 'upvote'
      post 'downvote'
    end 
  end 

  root 'songtopics#index'

end

app/models/songtopic.rb
class Songtopic < ActiveRecord::Base
	has_many :votes, dependent:  :destroy
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :songtopic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songtopics_controller.rb
class SongtopicsController < ApplicationController
  before_action :set_songtopic, only: [:show, :edit, :update, :destroy]

  # GET /songtopics
  # GET /songtopics.json
  def index
    @songtopics = Songtopic.all
  end

  # GET /songtopics/1
  # GET /songtopics/1.json
  def show
  end

  # GET /songtopics/new
  def new
    @songtopic = Songtopic.new
  end

  # GET /songtopics/1/edit
  def edit
  end

  # POST /songtopics
  # POST /songtopics.json
  def create
    @songtopic = Songtopic.new(songtopic_params)

    respond_to do |format|
      if @songtopic.save
        format.html { redirect_to @songtopic, notice: 'Songtopic was successfully created.' }
        format.json { render :show, status: :created, location: @songtopic }
      else
        format.html { render :new }
        format.json { render json: @songtopic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songtopics/1
  # PATCH/PUT /songtopics/1.json
  def update
    respond_to do |format|
      if @songtopic.update(songtopic_params)
        format.html { redirect_to @songtopic, notice: 'Songtopic was successfully updated.' }
        format.json { render :show, status: :ok, location: @songtopic }
      else
        format.html { render :edit }
        format.json { render json: @songtopic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songtopics/1
  # DELETE /songtopics/1.json
  def destroy
    @songtopic.destroy
    respond_to do |format|
      format.html { redirect_to songtopics_url, notice: 'Songtopic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @topic = Songtopic.find(params[:id])
    @topic.votes.create
    redirect_to(songtopics_path)
  end

  def downvote
    @topic = Songtopic.find(params[:id])
    # if(@topic.votes > 0)
    @topic.votes.first.destroy
    # end
    redirect_to(songtopics_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_songtopic
      @songtopic = Songtopic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def songtopic_params
      params.require(:songtopic).permit(:name, :album)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songtopics_helper.rb
module SongtopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppSong</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songtopics/_form.html.erb
<%= form_for(@songtopic) do |f| %>
  <% if @songtopic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@songtopic.errors.count, "error") %> prohibited this songtopic from being saved:</h2>

      <ul>
      <% @songtopic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songtopics/edit.html.erb
<h1>Editing Songtopic</h1>

<%= render 'form' %>

<%= link_to 'Show', @songtopic %> |
<%= link_to 'Back', songtopics_path %>

app/views/songtopics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songtopics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songtopics.each do |songtopic| %>
      <tr>
        <td><%= songtopic.name %></td>
        <td><%= songtopic.album %></td>
        <td><%= pluralize(songtopic.votes.count, "vote") %></td>
        <td><%= button_to '+1', upvote_songtopic_path(songtopic), method: :post %></td>
        <td><%= button_to '-1', downvote_songtopic_path(songtopic), method: :post %></td>
        <td><%= link_to 'Show', songtopic %></td>
        <td><%= link_to 'Edit', edit_songtopic_path(songtopic) %></td>
        <td><%= link_to 'Destroy', songtopic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Songtopic', new_songtopic_path %>

app/views/songtopics/new.html.erb
<h1>New Songtopic</h1>

<%= render 'form' %>

<%= link_to 'Back', songtopics_path %>

app/views/songtopics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @songtopic.name %>
</p>

<p>
  <strong>Album:</strong>
  <%= @songtopic.album %>
</p>

<%= link_to 'Edit', edit_songtopic_path(@songtopic) %> |
<%= link_to 'Back', songtopics_path %>